services:
  site:
    image: site-dev
    build: .
    volumes:
      - .:/srv/jekyll
    ports:
      - "4000:4000"
    working_dir: /srv/jekyll
    command: sh -c "bundle install && bundle exec jekyll serve --host 0.0.0.0 --force_polling"
